# coding: utf-8
from main import Secdef
secdef = Secdef()
secdef.load_instruments()
futures = secdef.get_count_by_type()
print(futures)
print('-'*30)
print()
futures_grouped_by_underlying = secdef.get_count_by_underlying()
print(futures_grouped_by_underlying)
print('-'*30)
print()
symbols = secdef.get_symbol()
print(symbols)
print('-'*30)
print()
secdef.pprint(futures_grouped_by_underlying)
print('-'*30)
print()
all_grouped_by_underlying = secdef.get_count_by_underlying(security_type='all')
secdef.pprint(all_grouped_by_underlying)
print('-'*30)
print()
symbols_10 = secdef.get_symbol(front_expiry_count=10)
print(symbols_10)
